version: '3.9'
services:
  postgres:
    image: "postgres"

  rabbitmq:
    image: "rabbitmq"

  api:
    build: "./notification-api"
    ports:
     - "4000:4000"
    depends_on:
      - rabbitmq

  api:
    build: "./notification-api"
    ports:
    - "4000:4000"
    depends_on:
      - rabbitmq
      - postgres
  
  service:
    build: "./notification-service"
    ports:
    - "4000:4000"
    depends_on:
      - rabbitmq
      - postgres

  cli:
    build: "./notification-cli"